services:
  - type: web
    name: negotiationbot
    env: docker
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_SERVER
        value: negobot-sqlsvr.database.windows.net
      - key: DB_NAME
        value: negobotchat
      - key: DB_PASSWORD
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PORT
        value: 1433  # SQL Server default
      - key: ENV
        value: production
